apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
  env:
    - name: DB_HOST
      valueFrom:
       secretKeyRef:
         name: {{ .Values.database.name }}-secret
         key: db_host
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: {{ .Values.database.name }}-secret
          key: db_name
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: {{ .Values.database.name }}-secret
          key: db_user
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Values.database.name }}-secret
          key: db_password
