apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.voting.name }}
  namespace: {{ .Values.voting.namespace }}
  labels:
    app: {{ .Values.voting.name }}
spec:
  type: {{ .Values.voting.service.type }}
  ports:
  - port: {{ .Values.voting.service.port }}
    targetPort: {{ .Values.voting.service.port }}
  selector:
    app: {{ .Values.voting.name }}