apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
   - secretName: {{ .Values.ingress.tlsSecretName }}
     hosts:
        - {{ .Values.ingress.host}}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
     paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ingress.serviceName }}
            port:
              number: {{ .Values.ingress.servicePort }}