apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.name }}-secret
  namespace: {{ .Values.database.namespace }}
type: Opaque
data:
  db_host: {{ .Values.database.host }}
  db_name: {{ .Values.database.name }}
  db_user: {{ .Values.database.user }}
  db_password: {{ .Values.database.password }}